### ISSUE TITLE
AttributeError: module 'jaxlib.gpu_triton' has no attribute 'TritonKernel'

### ISSUE THREAD

**Issue by adam-hartshorne** [jax-ml/jax-triton#167]
Following the instructions,

https://jax-ml.github.io/jax-triton/#installation-at-head 

i.e. pip install 'jax-triton @ git+https://github.com/jax-ml/jax-triton.git'

which install jax=0.4.11, jaxlib=0.4.11, triton=2.1.0, jax-trition=0.1.4,

Running on Ubuntu 22.04, Python 3.9.16, with CUDA 12.1

I get the following error
```
Traceback (most recent call last):
  File "/media/adam/shared_drive/PycharmProjects/triton_test/pallas_test.py", line 15, in <module>
    from jax_triton import pallas as pl
  File "/home/adam/anaconda3/envs/triton/lib/python3.9/site-packages/jax_triton/__init__.py", line 19, in <module>
    from jax_triton.triton_lib import triton_call
  File "/home/adam/anaconda3/envs/triton/lib/python3.9/site-packages/jax_triton/triton_lib.py", line 185, in <module>
    ) -> Tuple[triton_kernel_call_lib.TritonKernel, Any]:
AttributeError: module 'jaxlib.gpu_triton' has no attribute 'TritonKernel'
```

I also tried with jax/jaxlib=0.4.12, with the same result.

I have also tried a new environment running CUDA 11.8 with the everything else the same, with the same problem.

**Comment by sharadmv** [comment]
Did you install a jaxlib from HEAD using the instructions on the site?

**Comment by adam-hartshorne** [comment]
Yes, I tried that (including using latest version of jax).

Its worth noting that jaxlib head is incompatible with the version of jax that is pinned with jax-trition.

**Comment by sharadmv** [comment]
Thanks, I'll take a look

**Comment by sharadmv** [comment]
Is this issue fixed as of https://github.com/jax-ml/jax-triton/pull/169?

**Comment by adam-hartshorne** [comment]
I now get the following error message,

`import jax_triton as jt
`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adam/anaconda3/envs/triton/lib/python3.9/site-packages/jax_triton/__init__.py", line 22, in <module>
    from jax_triton import pallas
  File "/home/adam/anaconda3/envs/triton/lib/python3.9/site-packages/jax_triton/pallas/__init__.py", line 16, in <module>
    from jax_triton.pallas.core import BlockSpec
  File "/home/adam/anaconda3/envs/triton/lib/python3.9/site-packages/jax_triton/pallas/core.py", line 59, in <module>
    def current_grid_env() -> tuple[GridEnv, ...] | None:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
```

**Comment by sharadmv** [comment]
You'll need to use a newer python version I think

**Comment by sharadmv** [comment]
I could revert the python3.10 change as well

**Comment by adam-hartshorne** [comment]
I can confirm that after creating a new Python environment running python 3.10, I can import jax_triton without error. 

So yes it appears to be python 3.8 / 3.9 specific issue. As JAX supports 3.8+, at the very least I would have thought it needs to be noted somewhere that jax-triton requires a higher minimum version.

**Comment by sharadmv** [comment]
It's true that JAX does support 3.8+ but I think 3.8 support will soon be dropped. I'll double check the date to see whether it's worth fixing the typing issue.

**Comment by sharadmv** [comment]
JAX officially has dropped python3.8 support, so the upcoming jaxlib nightlies will no longer have 3.8 wheels.
