### ISSUE TITLE
Error Using Matrices For the Pallas Template Example

### ISSUE THREAD

**Issue by adam-hartshorne** [jax-ml/jax-triton#170]
The Pallas Template example works fine with an input, x, of shape (1,). However, when attempting to generalise the pallas template example (as shown in the code below), it produces the following error,

```
    x = pl.load(x_ref, ())
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax_triton/pallas/primitives.py", line 477, in load
    idx = NDIndexer.from_indices_shape(idx, x_ref.shape)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax_triton/pallas/primitives.py", line 278, in from_indices_shape
    else i for i, s in zip(indices, shape))
ValueError: safe_zip() argument 2 is longer than argument 1
```

Minimal example:
```
from jax_triton import pallas as pl
import jax
import jax.numpy as jnp
import jax.random as jnr

def make_kernel(eltwise_kernel):
  def add(x_ref, y_ref, o_ref):
    x = pl.load(x_ref, ())
    y = pl.load(y_ref, ())
    pl.store(o_ref, (), eltwise_kernel(x + y))
  return add

kernel1 = make_kernel(lambda x: x * 2)
kernel2 = make_kernel(jnp.exp)

def main(unused_argv):
  # x = jnp.array(1.)

  key = jnr.PRNGKey(0)
  key, subkey = jnr.split(key)

  x = jnr.normal(key, (100, 100))
  y = jnr.normal(subkey, (100, 100))

  m, k = x.shape
  n, _ = y.shape
  out_shape = jax.ShapeDtypeStruct(shape=(m, n), dtype=x.dtype)

  block_size_m = 10
  block_size_n = 10
  grid = (m // block_size_m * n // block_size_n,)

  print(pl.pallas_call(kernel1, out_shape=out_shape, grid=grid)(x, y))
  print(pl.pallas_call(kernel2, out_shape=out_shape, grid=grid)(x, y))

if __name__ == "__main__":
  from absl import app
  app.run(main)
```

The full trace is as follows,

```
Traceback (most recent call last):
  File "/media/adam/shared_drive/PycharmProjects/triton_test/pallas_test.py", line 53, in <module>
    app.run(main)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/media/adam/shared_drive/PycharmProjects/triton_test/pallas_test.py", line 48, in main
    print(pl.pallas_call(kernel1, out_shape=out_shape, grid=grid)(x, y))
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/pjit.py", line 250, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/pjit.py", line 158, in _python_pjit_helper
    args_flat, _, params, in_tree, out_tree, _ = infer_params_fn(
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/api.py", line 300, in infer_params
    return pjit.common_infer_params(pjit_info_args, *args, **kwargs)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/pjit.py", line 499, in common_infer_params
    jaxpr, consts, canonicalized_out_shardings_flat = _pjit_jaxpr(
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/pjit.py", line 961, in _pjit_jaxpr
    jaxpr, final_consts, out_type = _create_pjit_jaxpr(
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/linear_util.py", line 345, in memoized_fun
    ans = call(fun, *args)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/pjit.py", line 914, in _create_pjit_jaxpr
    jaxpr, global_out_avals, consts = pe.trace_to_jaxpr_dynamic(
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/interpreters/partial_eval.py", line 2155, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/interpreters/partial_eval.py", line 2177, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax_triton/pallas/pallas_call.py", line 348, in wrapped
    jaxpr, consts, _ = _initial_style_open_jaxpr(f, jaxpr_in_tree,
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax_triton/pallas/pallas_call.py", line 308, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/interpreters/partial_eval.py", line 2155, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/interpreters/partial_eval.py", line 2177, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/media/adam/shared_drive/PycharmProjects/triton_test/pallas_test.py", line 22, in add
    x = pl.load(x_ref, ())
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax_triton/pallas/primitives.py", line 477, in load
    idx = NDIndexer.from_indices_shape(idx, x_ref.shape)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax_triton/pallas/primitives.py", line 278, in from_indices_shape
    else i for i, s in zip(indices, shape))
jax._src.traceback_util.UnfilteredStackTrace: ValueError: safe_zip() argument 2 is longer than argument 1
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/media/adam/shared_drive/PycharmProjects/triton_test/pallas_test.py", line 48, in main
    print(pl.pallas_call(kernel1, out_shape=out_shape, grid=grid)(x, y))
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax_triton/pallas/pallas_call.py", line 348, in wrapped
    jaxpr, consts, _ = _initial_style_open_jaxpr(f, jaxpr_in_tree,
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax_triton/pallas/pallas_call.py", line 308, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File "/media/adam/shared_drive/PycharmProjects/triton_test/pallas_test.py", line 22, in add
    x = pl.load(x_ref, ())
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax_triton/pallas/primitives.py", line 477, in load
    idx = NDIndexer.from_indices_shape(idx, x_ref.shape)
  File "/home/adam/anaconda3/envs/triton_test/lib/python3.10/site-packages/jax_triton/pallas/primitives.py", line 278, in from_indices_shape
    else i for i, s in zip(indices, shape))
ValueError: safe_zip() argument 2 is longer than argument 1
python-BaseException
```

**Comment by sharadmv** [comment]
Sorry this is a bad error. However, for `pl.load` you need to explicitly specify an indexer for each dimension:
```
x = pl.load(x_ref, (slice(None), slice(None)))
y = pl.load(y_ref, (slice(None), slice(None)))
```

Does that fix the error? I'll keep this issue open since there's clear room for improvement on this.

**Comment by adam-hartshorne** [comment]
```
def make_kernel(eltwise_kernel):
  def add(x_ref, y_ref, o_ref):
    x = pl.load(x_ref, (slice(None), slice(None)))
    y = pl.load(y_ref, (slice(None), slice(None)))
    pl.store(o_ref, (slice(None), slice(None)), eltwise_kernel(x + y))
  return add
```

This works as long as the input matrices X and Y are of size = (n^2, n^2) e.g. (32 x 32). And this is true no matter what block sizes I set.

```
 bm = 32
 bn = 16
 grid = (jt.cdiv(m, bm), jt.cdiv(n, bn))
 print(pl.pallas_call(kernel1, out_shape=out_shape, grid=grid)(x, y))
 print(pl.pallas_call(kernel2, out_shape=out_shape, grid=grid)(x, y))
```

**Comment by sharadmv** [comment]
So when you specify a `grid` you are specifying how many parallel instances of the kernel you are invoking. In this case you'll be invoking the same kernel (m // bm * n // bn) times. However, the kernel you've written does the full elementwise addition for the whole matrix, so each is doing the same exact computation.

What you want is to *carve up* the computation across these different kernel instances so that they are doing disjoint work. To do this, you have a couple options. You can modify your indexing logic to use the `program_id` to pick a block.
```python
import jax
from jax_triton import pallas as pl
import jax.numpy as jnp

def make_kernel(eltwise_kernel, *, bm: int, bn: int):
  def add(x_ref, y_ref, o_ref):
    # What program instance are we in?
    i, j = pl.program_id(0), pl.program_id(1)
    # Let's select a block of the input matrices corresponding to our program id
    x = pl.load(x_ref, (pl.ds(i * bm, bm), pl.ds(j * bn, bn)))
    y = pl.load(y_ref, (pl.ds(i * bm, bm), pl.ds(j * bn, bn)))
    pl.store(o_ref, (pl.ds(i * bm, bm), pl.ds(j * bn, bn)), eltwise_kernel(x + y))
    o_ref[...] = eltwise_kernel(x_ref[...] + y_ref[...])
  return add

m, n = 256, 256
dtype = jnp.float32
out_shape = jax.ShapeDtypeStruct((m, n), dtype)
k1, k2 = jax.random.split(jax.random.PRNGKey(0))
x = jax.random.normal(k1, (m, n), dtype=dtype)
y = jax.random.normal(k2, (m, n), dtype=dtype)
bm = 32
bn = 16
kernel1 = make_kernel(lambda x: x * 2, bm=bm, bn=bn)
kernel2 = make_kernel(jnp.exp, bm=bm, bn=bn)
grid = (pl.cdiv(m, bm), pl.cdiv(n, bn))
print(pl.pallas_call(kernel1, out_shape=out_shape, grid=grid)(x, y))
print(pl.pallas_call(kernel2, out_shape=out_shape, grid=grid)(x, y))
```
OR, you can use `pl.BlockSpec` to specify how inputs/outputs are carved up.

```python
import jax
from jax_triton import pallas as pl
import jax.numpy as jnp

def make_kernel(eltwise_kernel):
  def add(x_ref, y_ref, o_ref):
    o_ref[...] = eltwise_kernel(x_ref[...] + y_ref[...])
  return add

m, n = 256, 256
dtype = jnp.float32
out_shape = jax.ShapeDtypeStruct((m, n), dtype)
k1, k2 = jax.random.split(jax.random.PRNGKey(0))
x = jax.random.normal(k1, (m, n), dtype=dtype)
y = jax.random.normal(k2, (m, n), dtype=dtype)
bm = 32
bn = 16
kernel1 = make_kernel(lambda x: x * 2)
kernel2 = make_kernel(jnp.exp)
grid = (pl.cdiv(m, bm), pl.cdiv(n, bn))
spec = pl.BlockSpec(lambda i, j: (i, j), (bm, bn))
print(pl.pallas_call(kernel1, in_specs=[spec, spec], out_specs=[spec], out_shape=out_shape, grid=grid)(x, y))
print(pl.pallas_call(kernel2, in_specs=[spec, spec], out_specs=[spec], out_shape=out_shape, grid=grid)(x, y))
```

**Comment by adam-hartshorne** [comment]
I apologise, I misunderstood the pallas capabilities. I was under the false impression that it was a wrapper around Triton that would handle carving up the data etc.

**Comment by sharadmv** [comment]
pl.BlockSpec does automatically do that for you

**Comment by adam-hartshorne** [comment]
I apologise for my ignorance, but is pl.BlockSpec also suppose to handle when the data is not exact multiples of the block size? Because if that is the case it doesn't work. 

However, the matmul example of pure triton code uses masking to handle this (as shown below). I presume you still need to use a pallas equivalent in order to correct handle any size input matrices?

```
@triton.jit
def matmul_kernel(
    # Pointers to matrices
    a_ptr, b_ptr, c_ptr,
    # Matrix dimensions
    M, N, K,
    # The stride variables represent how much to increase the ptr by when moving by 1
    # element in a particular dimension. E.g. `stride_am` is how much to increase `a_ptr`
    # by to get the element one row down (A has M rows).
    stride_am, stride_ak,
    stride_bk, stride_bn,
    stride_cm, stride_cn,
    # Meta-parameters
    block_size_m: tl.constexpr, block_size_n: tl.constexpr, block_size_k: tl.constexpr,
    group_size_m: tl.constexpr,
):
    """Kernel for computing the matmul C = A x B.
    A has shape (M, K), B has shape (K, N) and C has shape (M, N)
    """
    # -----------------------------------------------------------
    # Map program ids `pid` to the block of C it should compute.
    # This is done in a grouped ordering to promote L2 data reuse.
    # See above `L2 Cache Optimizations` section for details.
    pid = tl.program_id(axis=0)
    num_pid_m = tl.cdiv(M, block_size_m)
    num_pid_n = tl.cdiv(N, block_size_n)
    num_pid_in_group = group_size_m * num_pid_n
    group_id = pid // num_pid_in_group
    first_pid_m = group_id * group_size_m
    group_size_m = min(num_pid_m - first_pid_m, group_size_m)
    pid_m = first_pid_m + (pid % group_size_m)
    pid_n = (pid % num_pid_in_group) // group_size_m

    # ----------------------------------------------------------
    # Create pointers for the first blocks of A and B.
    # We will advance this pointer as we move in the K direction
    # and accumulate
    # `a_ptrs` is a block of [BLOCK_SIZE_M, BLOCK_SIZE_K] pointers
    # `b_ptrs` is a block of [BLOCK_SIZE_K, BLOCK_SIZE_N] pointers
    # See above `Pointer Arithmetics` section for details
    offs_am = (pid_m * block_size_m + tl.arange(0, block_size_m)) % M
    offs_bn = (pid_n * block_size_n + tl.arange(0, block_size_n)) % N
    offs_k = tl.arange(0, block_size_k)
    a_ptrs = a_ptr + (offs_am[:, None] * stride_am + offs_k[None, :] * stride_ak)
    b_ptrs = b_ptr + (offs_k[:, None] * stride_bk + offs_bn[None, :] * stride_bn)

    # -----------------------------------------------------------
    # Iterate to compute a block of the C matrix.
    # We accumulate into a `[BLOCK_SIZE_M, BLOCK_SIZE_N]` block
    # of fp32 values for higher accuracy.
    # `accumulator` will be converted back to fp16 after the loop.
    accumulator = tl.zeros((block_size_m, block_size_n), dtype=tl.float32)
    for k in range(0, tl.cdiv(K, block_size_k)):
        # Load the next block of A and B, generate a mask by checking the K dimension.
        # If it is out of bounds, set it to 0.
        a = tl.load(a_ptrs, mask=offs_k[None, :] < K - k * block_size_k, other=0.0)
        b = tl.load(b_ptrs, mask=offs_k[:, None] < K - k * block_size_k, other=0.0)
        # We accumulate along the K dimension.
        accumulator += tl.dot(a, b)

        # x_sum = tl.sum(a * a, axis=1)
        # y_sum = tl.sum(b * b, axis=0)
        # accumulator += x_sum[:, None] + y_sum[None, :] - 2.0 * tl.dot(a, b)

        # Advance the ptrs to the next K block.
        a_ptrs += block_size_k * stride_ak
        b_ptrs += block_size_k * stride_bk
    # You can fuse arbitrary activation functions here
    # while the accumulator is still in FP32!
    # if ACTIVATION == "leaky_relu":
    #     accumulator = leaky_relu(accumulator)
    c = accumulator.to(tl.float16)

    # -----------------------------------------------------------
    # Write back the block of the output matrix C with masks.
    offs_cm = pid_m * block_size_m + tl.arange(0, block_size_m)
    offs_cn = pid_n * block_size_n + tl.arange(0, block_size_n)
    c_ptrs = c_ptr + stride_cm * offs_cm[:, None] + stride_cn * offs_cn[None, :]
    c_mask = (offs_cm[:, None] < M) & (offs_cn[None, :] < N)
    tl.store(c_ptrs, c, mask=c_mask)
```

**Comment by sharadmv** [comment]
You'll need to use pl.load(..., mask=<mask vector>, other=...) to handle masking.

Sorry, Pallas isn't fully documented yet and I'm working on that actively.

**Comment by adam-hartshorne** [comment]
FYI,

```
def make_kernel(eltwise_kernel, *, bm: int, bn: int):
  def add(x_ref, y_ref, o_ref):
    # What program instance are we in?
    i, j = pl.program_id(0), pl.program_id(1)
    # Let's select a block of the input matrices corresponding to our program id
    x = pl.load(x_ref, (pl.ds(i * bm, bm), pl.ds(j * bn, bn)))
    y = pl.load(y_ref, (pl.ds(i * bm, bm), pl.ds(j * bn, bn)))
    pl.store(o_ref, (pl.ds(i * bm, bm), pl.ds(j * bn, bn)), eltwise_kernel(x + y))
    -> o_ref[...] = eltwise_kernel(x_ref[...] + y_ref[...])
  return add
```
I believe in the example you gave above, the marked line isn't correct / necessary, as you are already storing the result of eltwise_kernel to o_ref in the line above.

**Comment by sharadmv** [comment]
Thanks for the catch, fixed.
